# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2159ab7d6650f51e5b3cbdd9aeb06cbc515de9f406619256ae721d949d610aa7946f00382ebf348a93e50db0e8dca76b78493a6da61c453275d5016ab79db6e3

test:
  secret_key_base: 6df3f5cc5fc12c889f8e0963b9159a0c855625a2c9b1c6e13d2b76f4475b142f253476a9b3d7f7bab929d82904dec3835bae476a230fc0a079475840e6bdd77b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
